import { inflateSync } from 'node:zlib';
import { PDFDocument } from 'pdf-lib';
import {
  AGREEMENT_BRAND_FOOTER_PREFIX,
  buildAgreementBrandFooter,
  buildSignedLoanAgreementPdf,
  mapPartiesToSignatureImages,
} from './loan-agreement-pdf.builder';

/** Best-effort text extraction from FlateDecode content streams (pdf-lib). */
function extractPdfTextApprox(pdfBytes: Uint8Array): string {
  const raw = Buffer.from(pdfBytes).toString('latin1');
  const chunks: string[] = [];
  const re = /stream\r?\n([\s\S]*?)\r?\nendstream/g;
  let match: RegExpExecArray | null;
  while ((match = re.exec(raw))) {
    const payload = Buffer.from(match[1], 'binary');
    try {
      chunks.push(inflateSync(payload).toString('latin1'));
    } catch {
      chunks.push(payload.toString('latin1'));
    }
  }
  const content = chunks.join('\n');
  // pdf-lib draws WinAnsi as <HEX> Tj
  return content.replace(/<([0-9A-Fa-f]+)>/g, (_, hex: string) => {
    try {
      return Buffer.from(hex, 'hex').toString('latin1');
    } catch {
      return '';
    }
  });
}

const TINY_PNG = Buffer.from(
  'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg==',
  'base64',
);

describe('loan-agreement-pdf.builder', () => {
  it('maps party roles to DOCX signature image slots', () => {
    const images = mapPartiesToSignatureImages([
      {
        role: 'APPLICANT',
        signerName: 'A',
        signedAt: '2026-07-20T00:00:00.000Z',
        signaturePng: TINY_PNG,
      },
      {
        role: 'GUARANTOR',
        signerName: 'G',
        signedAt: '2026-07-20T00:00:00.000Z',
        signaturePng: TINY_PNG,
      },
      {
        role: 'OFFICER',
        signerName: 'O',
        signedAt: '2026-07-20T00:00:00.000Z',
        signaturePng: TINY_PNG,
      },
    ]);
    expect(images.borrower_signature).toBeTruthy();
    expect(images.guarantor_signature).toBeTruthy();
    expect(images.agent_signature).toBeTruthy();
  });

  it('builds a PDF without an ELECTRONIC SIGNATURES appendix', async () => {
    const result = await buildSignedLoanAgreementPdf({
      applicationId: '00000000-0000-4000-8000-000000000001',
      clientName: 'Jane Doe',
      phone: '+256700000000',
      nationalId: 'CF1234567890',
      principalAmount: 1_500_000,
      interestRatePercent: 10,
      durationDays: 90,
      loanDurationLabel: '90 days',
      processingFee: 0,
      collateralType: 'Motorcycle',
      loanPurpose: 'Business stock',
      district: 'Kampala',
      subCounty: 'Central',
      parish: 'Nakasero',
      village: 'Plot 1',
      guarantorName: 'John Guarantor',
      companyName: 'REMBEH Microfinance',
      companyAddress: 'Kampala Road',
      companyContact: '+256711111111',
      agentName: 'Agent Smith',
      agreementDate: new Date('2026-07-20T00:00:00.000Z'),
      dateLoanTaken: new Date('2026-07-20T00:00:00.000Z'),
      fineAmount: 15_000,
      finePeriodLabel: '1 day',
      version: 1,
      parties: [
        {
          role: 'APPLICANT',
          signerName: 'Jane Doe',
          signedAt: '2026-07-20T00:00:00.000Z',
          signaturePng: TINY_PNG,
        },
        {
          role: 'GUARANTOR',
          signerName: 'John Guarantor',
          signedAt: '2026-07-20T00:00:00.000Z',
          signaturePng: TINY_PNG,
        },
        {
          role: 'OFFICER',
          signerName: 'Agent Smith',
          signedAt: '2026-07-20T00:00:00.000Z',
          signaturePng: TINY_PNG,
        },
      ],
    });

    expect(result.pdfBytes.byteLength).toBeGreaterThan(500);
    expect(result.contentHash).toHaveLength(64);
    expect(result.source).toBe('docx-fields-fallback');

    const pdf = await PDFDocument.load(result.pdfBytes);
    const text = extractPdfTextApprox(result.pdfBytes);
    expect(text).toContain(AGREEMENT_BRAND_FOOTER_PREFIX);
    expect(text).toMatch(/20 July 2026|July 20,? 2026/);
    expect(text).not.toContain('Document version:');
    expect(text).not.toContain('LibreOffice PDF conversion unavailable');
    expect(text).not.toContain('ELECTRONIC SIGNATURES');
    expect(text).not.toContain('<<current_date>>');
    expect(text).toContain('LOAN AGREEMENT');
    expect(text).toContain('Jane Doe');
    expect(text).toContain('REMBEH Microfinance');
    expect(text).toContain('BETWEEN');
    expect(pdf.getPageCount()).toBeLessThanOrEqual(4);
  });

  it('builds the professional brand footer line', () => {
    expect(buildAgreementBrandFooter('20 July 2026')).toBe(
      'Generated by: Rembeh Financial Software (ANTIKRA Mechanism). Date: 20 July 2026',
    );
  });
});
