import { createHash } from 'node:crypto';
import { inflateSync } from 'node:zlib';
import {
  PDFDocument,
  StandardFonts,
  rgb,
  type PDFFont,
  type PDFPage,
} from 'pdf-lib';
import { convertDocxToPdfWithLibreOffice } from './loan-agreement-docx-to-pdf';
import {
  fillLoanAgreementDocx,
  resolveLoanAgreementTemplatePath,
  type LoanAgreementSignatureImages,
} from './loan-agreement-docx.merger';
import {
  buildLoanAgreementMergeFields,
  formatDate,
  type LoanAgreementFieldSource,
} from './loan-agreement-fields';

/**
 * Builds the signed loan agreement PDF from product-idea-assets/Loan-agreement .docx:
 * 1) Fill <<merge fields>> in the DOCX template (document + headers + footers)
 * 2) Embed signature PNGs inline at signature placeholders
 * 3) Prefer LibreOffice DOCX→PDF when it produces readable body text
 * 4) Otherwise render a professional pdf-lib fallback with the same layout
 *
 * IMPORTANT: never re-save LibreOffice PDFs through pdf-lib — load/save strips
 * CID-font body text and yields a near-blank page (signatures/footers only).
 *
 * Field mapping: see loan-agreement-fields.ts and docs/loan-agreement-fields.md
 */

export const AGREEMENT_BRAND_FOOTER_PREFIX =
  'Generated by: Rembeh Financial Software (ANTIKRA Mechanism). Date:';

export type SignedAgreementParty = {
  role: string;
  signerName: string;
  signedAt: string;
  /** PNG bytes for the signature image (optional if unavailable server-side). */
  signaturePng?: Uint8Array | null;
};

export type SignedAgreementInput = LoanAgreementFieldSource & {
  applicationId: string;
  processingFee: number | null;
  version: number;
  parties: SignedAgreementParty[];
};

export type SignedAgreementPdfResult = {
  pdfBytes: Uint8Array;
  contentHash: string;
  /** How the PDF body was produced (signatures embedded in DOCX when LibreOffice path used). */
  source: 'docx-libreoffice' | 'docx-fields-fallback';
};

export async function buildSignedLoanAgreementPdf(
  input: SignedAgreementInput,
): Promise<SignedAgreementPdfResult> {
  const fields = buildLoanAgreementMergeFields(input);
  const signatures = mapPartiesToSignatureImages(input.parties);
  const filledDocx = await fillLoanAgreementDocx(
    fields,
    resolveLoanAgreementTemplatePath(),
    signatures,
  );

  // Default to the reliable pdf-lib layout (always filled). Opt into LibreOffice
  // with LOAN_AGREEMENT_USE_LIBREOFFICE=1 — LO PDFs are accepted only when body
  // text is detectable (pdf-lib must never re-save them).
  const useLibreOffice =
    process.env.LOAN_AGREEMENT_USE_LIBREOFFICE?.trim() === '1';

  let bodyPdf: Uint8Array | null = null;
  let source: SignedAgreementPdfResult['source'] = 'docx-fields-fallback';

  if (useLibreOffice) {
    const loPdf = await convertDocxToPdfWithLibreOffice(filledDocx);
    if (loPdf && pdfLooksLikeFilledAgreement(loPdf)) {
      bodyPdf = loPdf;
      source = 'docx-libreoffice';
    }
  }

  if (!bodyPdf) {
    source = 'docx-fields-fallback';
    bodyPdf = await buildFallbackPdfFromTemplateFields(fields, signatures);
    // Fallback draws body; stamp brand footer once (safe — pdf-lib created this PDF).
    const generatedDate = formatDate(input.agreementDate ?? new Date());
    bodyPdf = await stampAgreementBrandFooter(bodyPdf, generatedDate);
  }

  const contentHash = createHash('sha256').update(bodyPdf).digest('hex');
  return { pdfBytes: bodyPdf, contentHash, source };
}

/**
 * LibreOffice PDFs use CID fonts; pdf-lib load/save often drops that body text.
 * Detect a usable conversion by looking for known agreement phrases in streams.
 */
export function pdfLooksLikeFilledAgreement(pdfBytes: Uint8Array): boolean {
  const raw = Buffer.from(pdfBytes);
  // Uncompressed markers / Latin strings LibreOffice may emit
  if (
    raw.includes(Buffer.from('LOAN AGREEMENT')) ||
    raw.includes(Buffer.from('THE REPUBLIC')) ||
    raw.includes(Buffer.from('BETWEEN')) ||
    raw.includes(Buffer.from('MONEYLENDERS'))
  ) {
    return true;
  }

  // FlateDecode content: inflate and search
  const asLatin = raw.toString('latin1');
  const re = /stream\r?\n([\s\S]*?)\r?\nendstream/g;
    let match: RegExpExecArray | null;
    let hit = false;
    while ((match = re.exec(asLatin))) {
      const payload = Buffer.from(match[1]!, 'binary');
      try {
        const dec = inflateSync(payload);
        const text = dec.toString('latin1');
        if (
          /LOAN AGREEMENT|THE REPUBLIC|BETWEEN|MONEYLENDERS|Borrower/i.test(text)
        ) {
          hit = true;
        }
      } catch {
        // ignore non-flate streams
      }
    }

  if (hit) return true;
  // Do not trust byte-size heuristics — blank LO PDFs can still embed large fonts.
  return false;
}

export function mapPartiesToSignatureImages(
  parties: SignedAgreementParty[],
): LoanAgreementSignatureImages {
  const images: LoanAgreementSignatureImages = {};
  for (const party of parties) {
    if (!party.signaturePng || party.signaturePng.byteLength === 0) continue;
    if (party.role === 'APPLICANT') {
      images.borrower_signature = party.signaturePng;
    } else if (party.role === 'GUARANTOR') {
      images.guarantor_signature = party.signaturePng;
    } else if (party.role === 'OFFICER') {
      images.agent_signature = party.signaturePng;
    }
  }
  return images;
}

export function buildAgreementBrandFooter(dateLabel: string): string {
  return `${AGREEMENT_BRAND_FOOTER_PREFIX} ${dateLabel}`;
}

/**
 * Centered brand footer on every page (LibreOffice + fallback).
 * Does not add "Document version" or LibreOffice-unavailable notices.
 */
export async function stampAgreementBrandFooter(
  pdfBytes: Uint8Array,
  dateLabel: string,
): Promise<Uint8Array> {
  const doc = await PDFDocument.load(pdfBytes);
  const font = await doc.embedFont(StandardFonts.TimesRoman);
  const footer = buildAgreementBrandFooter(dateLabel);
  const size = 8;
  const color = rgb(0.25, 0.28, 0.32);

  for (const page of doc.getPages()) {
    const { width } = page.getSize();
    const textWidth = font.widthOfTextAtSize(footer, size);
    page.drawText(footer, {
      x: Math.max(36, (width - textWidth) / 2),
      y: 28,
      size,
      font,
      color,
    });
  }

  return doc.save();
}

/**
 * Fallback when LibreOffice is unavailable: match DOCX template alignment —
 * centered legal header + LOAN AGREEMENT (underlined), left-aligned body,
 * indented sub-clauses, inline signature blocks, centered brand footer.
 * Prefer installing LibreOffice in prod for full DOCX fidelity.
 */
async function buildFallbackPdfFromTemplateFields(
  fields: Record<string, string>,
  signatures: LoanAgreementSignatureImages,
): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  const font = await doc.embedFont(StandardFonts.TimesRoman);
  const bold = await doc.embedFont(StandardFonts.TimesRomanBold);
  const pageWidth = 595.28;
  const pageHeight = 841.89;
  const left = 54;
  const right = 54;
  const maxWidth = pageWidth - left - right;
  const bottomSafe = 56;
  const topStart = pageHeight - 56;
  const ink = rgb(0.08, 0.1, 0.14);

  let page = doc.addPage([pageWidth, pageHeight]);
  let y = topStart;

  const ensureSpace = (needed: number) => {
    if (y < bottomSafe + needed) {
      page = doc.addPage([pageWidth, pageHeight]);
      y = topStart;
    }
  };

  const drawCentered = (
    text: string,
    size: number,
    useBold = false,
    gap = 5,
    underline = false,
  ) => {
    const activeFont = useBold ? bold : font;
    const lines = wrapText(text, activeFont, size, maxWidth);
    for (const line of lines) {
      ensureSpace(size + gap + 8);
      const textWidth = activeFont.widthOfTextAtSize(line, size);
      const x = (pageWidth - textWidth) / 2;
      page.drawText(line, { x, y, size, font: activeFont, color: ink });
      if (underline) {
        page.drawLine({
          start: { x, y: y - 2 },
          end: { x: x + textWidth, y: y - 2 },
          thickness: 1,
          color: ink,
        });
      }
      y -= size + gap;
    }
  };

  const drawLeft = (
    text: string,
    size = 11,
    useBold = false,
    gap = 4,
    indent = 0,
  ) => {
    const activeFont = useBold ? bold : font;
    const width = maxWidth - indent;
    const lines = wrapText(text, activeFont, size, width);
    for (const line of lines) {
      ensureSpace(size + gap + 6);
      page.drawText(line, {
        x: left + indent,
        y,
        size,
        font: activeFont,
        color: ink,
      });
      y -= size + gap;
    }
  };

  // ——— Header (centered) ———
  drawCentered('THE REPUBLIC OF UGANDA', 12, true, 6);
  drawCentered(
    'IN THE MATTER OF THE MONEYLENDERS ACT, CAP.273',
    11,
    true,
    5,
  );
  drawCentered('AND', 11, true, 5);
  drawCentered(
    `IN THE MATTER OF ${fields.company_name.toUpperCase()}`,
    11,
    true,
    8,
  );
  drawCentered('LOAN AGREEMENT', 14, true, 14, true);

  // ——— Body (left-aligned) ———
  drawLeft(
    `This loan agreement made this ${fields.day} day of ${fields.month}, ${fields.year}`,
    11,
    false,
    10,
  );

  drawLeft('BETWEEN', 11, true, 8);
  drawLeft(
    `${fields.company_name}, ${fields.company_address}, ${fields.company_contact} (hereafter referred to as "The Lender") of the one part`,
    11,
    false,
    10,
  );

  drawLeft('AND', 11, true, 8);
  drawLeft(
    `${fields.borrowername}, ${fields.NIN} Of Residential address ${fields.borrower_address} Telephone Number(s) ${fields.borrower_contact} (Hereafter referred as "The Borrower") of the other part.`,
    11,
    false,
    10,
  );

  drawLeft(
    `WHEREAS The Borrower has applied to The Lender for a loan in the sum of UGX ${fields.amount_borrowed} and`,
    11,
    false,
    8,
  );
  drawLeft('NOW THEREFORE, this agreement witness as follows:', 11, true, 12);

  drawLeft('1. THE LOAN', 12, true, 6);
  drawLeft(
    `The Lender hereby agrees to loan The Borrower the sum of Ug. Shs ${fields.amount_borrowed_in_words}.`,
    11,
    false,
    10,
  );

  drawLeft('2. THE PURPOSE OF THE LOAN', 12, true, 6);
  drawLeft(
    `The Borrower shall apply the loan towards ${fields.loan_purpose}`,
    11,
    false,
    10,
  );

  // Keep DOCX spelling "INTREST" for template fidelity.
  drawLeft('3. INTREST', 12, true, 6);
  drawLeft(
    `An interest of ${fields.interest_rate} of the borrowed amount will be paid on top of the loaned amount at the end of the loan period.`,
    11,
    false,
    10,
  );

  drawLeft('4. REPAYMENT', 12, true, 6);
  drawLeft(
    `a) The Borrower hereby agrees and undertakes to repay the said loan and interest within only ${fields.loan_duration} from ${fields.date_loan_taken} (the date of disbursement of the said loan), unless decided and agreed otherwise by the loans committee.`,
    11,
    false,
    8,
    14,
  );
  drawLeft(
    `b) The Borrower hereby agrees that if the said loan is not paid within the AGREED loan period, an amount of UGX. ${fields.fine_amount} will be charged for EVERY additional ${fields.fine_period} beyond the agreed loan period.`,
    11,
    false,
    10,
    14,
  );

  drawLeft('5. SECURITY', 12, true, 6);
  drawLeft(
    'i) As security for repayment of the said loan and interest, The Borrower hereby pledges to The Lender the following;',
    11,
    false,
    6,
    14,
  );
  drawLeft(`a) ${fields.collateral_1}`, 11, false, 8, 28);
  drawLeft(
    'ii) The Borrower hereby agrees that in case of default, The Lender shall take legal actions against The Borrower to recover all the amounts including the legal and other costs.',
    11,
    false,
    16,
    14,
  );

  // Inline signature blocks (as in DOCX — not an ELECTRONIC SIGNATURES appendix)
  ensureSpace(120);
  drawLeft('The Borrower', 11, true, 8);
  y = await drawNameSignatureRow(
    page,
    doc,
    font,
    bold,
    left,
    maxWidth,
    y,
    fields.borrower_name,
    signatures.borrower_signature,
    ink,
  );

  ensureSpace(120);
  drawLeft('Guarantor', 11, true, 8);
  y = await drawNameSignatureRow(
    page,
    doc,
    font,
    bold,
    left,
    maxWidth,
    y,
    fields.gurantor_name,
    signatures.guarantor_signature,
    ink,
  );

  ensureSpace(120);
  drawLeft(`On Behalf of ${fields.company_name}`, 11, true, 8);
  y = await drawNameSignatureRow(
    page,
    doc,
    font,
    bold,
    left,
    maxWidth,
    y,
    fields.agent_name,
    signatures.agent_signature,
    ink,
  );

  void y;
  return doc.save();
}

async function drawNameSignatureRow(
  page: PDFPage,
  doc: PDFDocument,
  font: PDFFont,
  bold: PDFFont,
  left: number,
  maxWidth: number,
  y: number,
  name: string,
  signaturePng: Uint8Array | null | undefined,
  ink: ReturnType<typeof rgb>,
): Promise<number> {
  const size = 11;
  const nameLabel = `Name: ${name}`;
  page.drawText(nameLabel, {
    x: left,
    y,
    size,
    font,
    color: ink,
  });

  const sigLabel = 'Signature:';
  const midX = left + maxWidth * 0.52;
  page.drawText(sigLabel, {
    x: midX,
    y,
    size,
    font: bold,
    color: ink,
  });

  let nextY = y - size - 6;
  if (signaturePng && signaturePng.byteLength > 0) {
    try {
      const image = await doc.embedPng(signaturePng);
      const maxSigWidth = 160;
      const maxSigHeight = 48;
      const scale = Math.min(
        maxSigWidth / image.width,
        maxSigHeight / image.height,
        1,
      );
      const width = image.width * scale;
      const height = image.height * scale;
      page.drawImage(image, {
        x: midX,
        y: nextY - height,
        width,
        height,
      });
      nextY = nextY - height - 14;
      return nextY;
    } catch {
      // fall through
    }
  }

  // Signature line when image missing
  page.drawLine({
    start: { x: midX + 58, y: y + 2 },
    end: { x: left + maxWidth, y: y + 2 },
    thickness: 0.6,
    color: ink,
  });
  return nextY - 12;
}

function wrapText(
  text: string,
  font: PDFFont,
  size: number,
  maxWidth: number,
): string[] {
  const words = text.split(/\s+/).filter(Boolean);
  if (words.length === 0) return [''];
  const lines: string[] = [];
  let current = words[0]!;
  for (let i = 1; i < words.length; i += 1) {
    const next = `${current} ${words[i]}`;
    if (font.widthOfTextAtSize(next, size) <= maxWidth) {
      current = next;
    } else {
      lines.push(current);
      current = words[i]!;
    }
  }
  lines.push(current);
  return lines;
}
