import { createHash } from 'node:crypto';
import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';

export type SignedAgreementParty = {
  role: string;
  signerName: string;
  signedAt: string;
  /** PNG bytes for the signature image (optional if unavailable server-side). */
  signaturePng?: Uint8Array | null;
};

export type SignedAgreementInput = {
  applicationId: string;
  clientName: string;
  phone: string | null;
  nationalId: string | null;
  principalAmount: number | null;
  interestRatePercent: number | null;
  durationDays: number | null;
  processingFee: number | null;
  collateralType: string | null;
  district: string | null;
  subCounty: string | null;
  parish: string | null;
  village: string | null;
  guarantorName: string | null;
  version: number;
  parties: SignedAgreementParty[];
};

export type SignedAgreementPdfResult = {
  pdfBytes: Uint8Array;
  contentHash: string;
};

/**
 * Builds a simple signed loan agreement PDF embedding signature images
 * and key loan fields. Uses pdf-lib (no native deps).
 */
export async function buildSignedLoanAgreementPdf(
  input: SignedAgreementInput,
): Promise<SignedAgreementPdfResult> {
  const doc = await PDFDocument.create();
  const page = doc.addPage([595.28, 841.89]); // A4
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);

  let y = 800;
  const left = 50;
  const line = (text: string, size = 11, useBold = false) => {
    page.drawText(text, {
      x: left,
      y,
      size,
      font: useBold ? bold : font,
      color: rgb(0.1, 0.12, 0.18),
    });
    y -= size + 8;
  };

  line('REMBEH — Signed Loan Agreement', 18, true);
  line(`Document version: ${input.version}`, 10);
  line(`Application ID: ${input.applicationId}`, 10);
  y -= 6;

  line('Borrower & loan terms', 13, true);
  line(`Borrower: ${input.clientName || '—'}`);
  line(`Phone: ${input.phone || '—'}`);
  line(`National ID: ${input.nationalId || '—'}`);
  line(
    `Location: ${[input.district, input.subCounty, input.parish, input.village]
      .filter(Boolean)
      .join(' / ') || '—'}`,
  );
  line(`Principal: ${formatMoney(input.principalAmount)}`);
  line(`Interest rate: ${formatPercent(input.interestRatePercent)}`);
  line(`Duration (days): ${input.durationDays ?? '—'}`);
  line(`Processing fee: ${formatMoney(input.processingFee)}`);
  line(`Collateral: ${input.collateralType || '—'}`);
  line(`Guarantor: ${input.guarantorName || '—'}`);
  y -= 8;

  line(
    'By signing electronically, each party agrees this signature has the same legal effect as a handwritten signature on a paper agreement.',
    9,
  );
  y -= 12;

  for (const party of input.parties) {
    if (y < 180) {
      // Keep signatures on one page when possible; truncate further layout.
      break;
    }
    line(`${party.role}: ${party.signerName}`, 12, true);
    line(`Signed at: ${party.signedAt}`, 9);

    if (party.signaturePng && party.signaturePng.byteLength > 0) {
      try {
        const image = await doc.embedPng(party.signaturePng);
        const maxWidth = 220;
        const maxHeight = 70;
        const scale = Math.min(
          maxWidth / image.width,
          maxHeight / image.height,
          1,
        );
        const width = image.width * scale;
        const height = image.height * scale;
        page.drawImage(image, {
          x: left,
          y: y - height,
          width,
          height,
        });
        y -= height + 16;
      } catch {
        line('[Signature image could not be embedded]', 9);
      }
    } else {
      line('[Signature on file in object storage]', 9);
      y -= 8;
    }
  }

  line('Generated by REMBEH electronic signature system.', 8);
  const pdfBytes = await doc.save();
  const contentHash = createHash('sha256').update(pdfBytes).digest('hex');
  return { pdfBytes, contentHash };
}

function formatMoney(value: number | null) {
  if (value === null || value === undefined || Number.isNaN(value)) return '—';
  return `UGX ${value.toLocaleString('en-UG', { maximumFractionDigits: 0 })}`;
}

function formatPercent(value: number | null) {
  if (value === null || value === undefined || Number.isNaN(value)) return '—';
  return `${value}%`;
}
