import {
  formatDate,
  formatMoneyAmount,
  titleCase,
} from "../../app/owner/owner-common";
import {
  documentReportStatusLabel,
  type DailyReportDocumentModel,
} from "./daily-reconciliation-report";
import { dailyReportCode } from "./reports-filters";

export const REMBEH_WEB_URL = "https://rembeh.antikra.com";
export const REMBEH_BRAND_NAME = "REMBEH";
/** Public Rembeh mark used on generated PDFs. */
export const REMBEH_MARK_URL = "/assets/brand/rembeh-mark.png";
/** Bump when PDF chrome changes so in-memory caches regenerate. */
export const DAILY_REPORT_PDF_LAYOUT_VERSION = "v2-rembeh-brand";

const EMERALD: [number, number, number] = [6, 91, 36];
const NAVY: [number, number, number] = [20, 33, 61];
const SLATE: [number, number, number] = [39, 48, 63];
const MUTED: [number, number, number] = [107, 114, 128];
const LINE: [number, number, number] = [213, 221, 216];
const GREEN_FILL: [number, number, number] = [239, 248, 242];
const RED_FILL: [number, number, number] = [254, 243, 242];
const RED: [number, number, number] = [180, 35, 24];
const HEADER_FILL: [number, number, number] = [247, 248, 250];

type JsPdfDoc = import("jspdf").jsPDF & {
  lastAutoTable?: { finalY: number };
  autoTable: (options: Record<string, unknown>) => void;
};

function money(value: number) {
  return formatMoneyAmount(value);
}

function shortName(fullName: string) {
  const parts = fullName
    .trim()
    .split(/\s+/)
    .filter(Boolean);
  if (parts.length === 0) return "—";
  if (parts.length === 1) return parts[0]!.toUpperCase();
  const surname = parts[0]!.toUpperCase();
  const given = parts[parts.length - 1]!;
  return `${surname} ${given[0]!.toUpperCase()}.`;
}

function formatTime(value: string | null | undefined) {
  if (!value) return "—";
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return "—";
  return date.toLocaleTimeString("en-UG", {
    hour: "numeric",
    minute: "2-digit",
  });
}

function formatDateTime(value: string) {
  return new Date(value).toLocaleString("en-UG", {
    day: "numeric",
    month: "short",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });
}

function categoryLabel(raw: string, paidFrom?: string) {
  if (paidFrom === "AGENT_FLOAT") return "Field float";
  if (raw.toUpperCase() === "OTHER") return "Expense";
  return titleCase(raw.replaceAll("_", " "));
}

function methodLabel(raw: string | null | undefined) {
  if (!raw?.trim()) return "Cash";
  return titleCase(raw.replaceAll("_", " "));
}

export function dailyReportPdfFingerprint(document: DailyReportDocumentModel) {
  return [
    DAILY_REPORT_PDF_LAYOUT_VERSION,
    document.reportNumber,
    document.status,
    document.generatedAt,
    document.operationDate,
    document.branchName,
  ].join("|");
}

export function dailyReportPdfFileName(document: DailyReportDocumentModel) {
  const code =
    document.displayReportNumber ??
    dailyReportCode(document.operationDate) ??
    document.reportNumber;
  const branch = document.branchName
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-");
  return `rembeh-${branch || "branch"}-${code || document.operationDate}.pdf`;
}

export function dailyReportShareMessage(document: DailyReportDocumentModel) {
  const dateLabel = formatDate(document.operationDate);
  return [
    `Daily Reconciliation Report — ${dateLabel}`,
    document.branchName,
    "",
    "Shared from REMBEH",
    "Generated by REMBEH",
    REMBEH_WEB_URL,
  ].join("\n");
}

/** Build a real PDF blob matching the mobile daily report layout. */
export async function buildDailyReconciliationPdfBlob(
  document: DailyReportDocumentModel,
): Promise<Blob> {
  const [{ jsPDF }, autoTableModule] = await Promise.all([
    import("jspdf"),
    import("jspdf-autotable"),
  ]);
  const autoTable =
    (autoTableModule as { default?: (doc: unknown, opts: unknown) => void })
      .default ??
    (autoTableModule as unknown as (doc: unknown, opts: unknown) => void);

  const doc = new jsPDF({
    orientation: "portrait",
    unit: "pt",
    format: "a4",
  }) as JsPdfDoc;

  const mark = await loadRembehMark(doc);

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 36;
  const contentWidth = pageWidth - margin * 2;
  let y = margin;

  const ensureSpace = (needed: number) => {
    if (y + needed <= pageHeight - 42) return;
    doc.addPage();
    y = margin;
    drawPageChrome(doc, document, pageWidth, pageHeight, margin, false);
  };

  const sectionTitle = (title: string) => {
    ensureSpace(28);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(...EMERALD);
    doc.text(title, margin, y);
    y += 14;
  };

  drawPageChrome(doc, document, pageWidth, pageHeight, margin, true);
  y = drawTitleBlock(doc, document, margin, contentWidth, y + 8, mark);

  // Closing cards
  ensureSpace(70);
  y = drawMetricCards(doc, document, margin, contentWidth, y);

  sectionTitle("1. CASH POSITION SUMMARY");
  y = drawCashMovement(doc, document, margin, contentWidth, y);

  sectionTitle("2. FIELD OFFICER ACCOUNTABILITY");
  y = drawAgentTable(doc, autoTable, document, margin, y);

  sectionTitle("3. LOANS ISSUED TODAY");
  y = drawLoansTable(doc, autoTable, document, margin, y);

  sectionTitle("4. REPAYMENTS COLLECTED");
  y = drawRepaymentsTable(doc, autoTable, document, margin, y);

  sectionTitle("5. PROCESSING FEES");
  y = drawFeesTable(doc, autoTable, document, margin, y);

  sectionTitle("6. EXPENSES");
  y = drawExpensesTable(doc, autoTable, document, margin, y);

  if (document.variances.length > 0) {
    sectionTitle("7. DISCREPANCIES");
    y = drawVariancesTable(doc, autoTable, document, margin, y);
  }

  const notes =
    document.closingNotes?.trim() || document.managerNotes?.trim() || "";
  if (notes) {
    sectionTitle(
      document.variances.length > 0
        ? "8. RECONCILIATION NOTES"
        : "7. RECONCILIATION NOTES",
    );
    ensureSpace(48);
    doc.setFillColor(...HEADER_FILL);
    doc.setDrawColor(...LINE);
    doc.roundedRect(margin, y, contentWidth, 40, 4, 4, "FD");
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(...SLATE);
    const lines = doc.splitTextToSize(notes, contentWidth - 16);
    doc.text(lines, margin + 8, y + 14);
    y += Math.max(40, lines.length * 12 + 16);
  }

  // Footer on all pages
  const total = doc.getNumberOfPages();
  for (let page = 1; page <= total; page += 1) {
    doc.setPage(page);
    drawFooter(doc, document, page, total, pageWidth, pageHeight, margin);
  }

  return doc.output("blob");
}

function drawPageChrome(
  doc: JsPdfDoc,
  document: DailyReportDocumentModel,
  pageWidth: number,
  pageHeight: number,
  margin: number,
  firstPage: boolean,
) {
  if (firstPage) return;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.setTextColor(...EMERALD);
  doc.text(REMBEH_BRAND_NAME, margin, margin - 12);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...MUTED);
  doc.text(
    `${document.branchName} · ${formatDate(document.operationDate)}`,
    pageWidth - margin,
    margin - 12,
    { align: "right" },
  );
  doc.setDrawColor(...LINE);
  doc.line(margin, margin - 6, pageWidth - margin, margin - 6);
  void pageHeight;
}

function drawFooter(
  doc: JsPdfDoc,
  document: DailyReportDocumentModel,
  page: number,
  total: number,
  pageWidth: number,
  pageHeight: number,
  margin: number,
) {
  const y = pageHeight - 22;
  doc.setDrawColor(...LINE);
  doc.line(margin, y - 8, pageWidth - margin, y - 8);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  doc.setTextColor(...MUTED);
  doc.text(
    `Generated by REMBEH · rembeh.antikra.com · ${document.branchName}`,
    margin,
    y,
  );
  doc.text(`Page ${page} of ${total}`, pageWidth - margin, y, {
    align: "right",
  });
}

function drawTitleBlock(
  doc: JsPdfDoc,
  document: DailyReportDocumentModel,
  margin: number,
  contentWidth: number,
  startY: number,
  mark: string | null,
) {
  let y = startY;
  const center = margin + contentWidth / 2;

  if (mark) {
    const size = 42;
    doc.setFillColor(...GREEN_FILL);
    doc.setDrawColor(...LINE);
    doc.roundedRect(center - size / 2, y, size, size, 8, 8, "FD");
    doc.addImage(mark, "PNG", center - 15, y + 6, 30, 30);
    y += size + 10;
  } else {
    doc.setFillColor(...EMERALD);
    doc.roundedRect(center - 11, y, 22, 22, 4, 4, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.text("R", center, y + 15, { align: "center" });
    y += 34;
  }

  doc.setTextColor(...EMERALD);
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text(REMBEH_BRAND_NAME, center, y, { align: "center" });
  y += 14;
  doc.setTextColor(...SLATE);
  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.text(document.branchName.toUpperCase(), center, y, { align: "center" });
  y += 12;
  doc.setDrawColor(...EMERALD);
  doc.setLineWidth(1.2);
  doc.line(margin + 40, y, margin + contentWidth - 40, y);
  y += 16;
  doc.setTextColor(...EMERALD);
  doc.setFontSize(11);
  doc.text("DAILY RECONCILIATION REPORT", center, y, { align: "center" });
  y += 16;
  doc.setTextColor(...MUTED);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.text("Report Date", center, y, { align: "center" });
  y += 12;
  doc.setTextColor(...NAVY);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text(formatDate(document.operationDate), center, y, { align: "center" });
  y += 18;

  const meta = [
    ["Manager", document.preparedBy],
    ["Status", documentReportStatusLabel(document.status)],
    ["Generated", formatDateTime(document.preparedOn || document.generatedAt)],
  ];
  const colW = contentWidth / 3;
  meta.forEach(([label, value], index) => {
    const x = margin + colW * index + colW / 2;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7.5);
    doc.setTextColor(...MUTED);
    doc.text(label!, x, y, { align: "center" });
    doc.setFont("helvetica", "bold");
    doc.setFontSize(8.5);
    doc.setTextColor(...NAVY);
    doc.text(value!, x, y + 11, { align: "center" });
  });
  return y + 28;
}

async function loadRembehMark(doc: JsPdfDoc): Promise<string | null> {
  try {
    const response = await fetch(REMBEH_MARK_URL);
    if (!response.ok) return null;
    const buffer = await response.arrayBuffer();
    const bytes = new Uint8Array(buffer);
    let binary = "";
    for (let i = 0; i < bytes.length; i += 1) {
      binary += String.fromCharCode(bytes[i]!);
    }
    const dataUrl = `data:image/png;base64,${btoa(binary)}`;
    // Warm image into jsPDF format registry.
    void doc;
    return dataUrl;
  } catch {
    return null;
  }
}

function drawMetricCards(
  doc: JsPdfDoc,
  document: DailyReportDocumentModel,
  margin: number,
  contentWidth: number,
  startY: number,
) {
  const gap = 8;
  const cardW = (contentWidth - gap * 2) / 3;
  const variance = document.variance;
  const cards: Array<{
    label: string;
    value: string;
    color: [number, number, number];
  }> = [
    {
      label: "Expected closing",
      value: `${document.currency} ${money(document.expectedClosingBalance)}`,
      color: NAVY,
    },
    {
      label: "Counted closing",
      value:
        document.countedCash == null
          ? "—"
          : `${document.currency} ${money(document.countedCash)}`,
      color: NAVY,
    },
    {
      label: "Variance",
      value:
        variance == null ? "—" : `${document.currency} ${money(variance)}`,
      color:
        variance == null
          ? NAVY
          : variance < 0
            ? RED
            : variance > 0
              ? EMERALD
              : NAVY,
    },
  ];

  cards.forEach((card, index) => {
    const x = margin + index * (cardW + gap);
    doc.setFillColor(248, 250, 249);
    doc.setDrawColor(...LINE);
    doc.roundedRect(x, startY, cardW, 48, 5, 5, "FD");
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7.5);
    doc.setTextColor(...MUTED);
    doc.text(card.label, x + 10, startY + 16);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(...card.color);
    doc.text(card.value, x + 10, startY + 34);
  });
  return startY + 62;
}

function drawCashMovement(
  doc: JsPdfDoc,
  document: DailyReportDocumentModel,
  margin: number,
  contentWidth: number,
  startY: number,
) {
  const gap = 10;
  const colW = (contentWidth - gap) / 2;
  const topUps =
    document.topUpsTotal ||
    document.topUps.reduce((sum, row) => sum + row.amount, 0);
  const shortage = document.shortageRecoveriesTotal ?? 0;
  const additions =
    document.openingBalance +
    topUps +
    document.collectionsReceived +
    document.processingFeesTotal +
    shortage;
  const salaries = document.salariesTotal ?? 0;
  const cashouts =
    document.expensesTotal + salaries + document.loansIssuedPrincipal;

  const leftLines: Array<[string, number, "plain" | "in" | "out"]> = [
    ["Opening Balance", document.openingBalance, "plain"],
    ["Capital received", topUps, "plain"],
    ["Cash in", document.collectionsReceived, "in"],
    ["Processing fees", document.processingFeesTotal, "in"],
    ["Shortage cleared", shortage, "in"],
  ];
  const rightLines: Array<[string, number, "plain" | "in" | "out"]> = [
    ["Total Expenses", document.expensesTotal, "out"],
    ["Salary", salaries, "out"],
    ["Loans issued", document.loansIssuedPrincipal, "out"],
  ];

  const blockH = Math.max(leftLines.length, rightLines.length) * 16 + 48;

  const paintBlock = (
    x: number,
    title: string,
    titleColor: [number, number, number],
    fill: [number, number, number],
    lines: Array<[string, number, "plain" | "in" | "out"]>,
    total: number,
  ) => {
    doc.setDrawColor(...LINE);
    doc.setFillColor(255, 255, 255);
    doc.roundedRect(x, startY, colW, blockH, 5, 5, "FD");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.setTextColor(...titleColor);
    doc.text(title, x + 10, startY + 16);
    let ly = startY + 30;
    for (const [label, value, tone] of lines) {
      doc.setFont("helvetica", "normal");
      doc.setFontSize(8.5);
      doc.setTextColor(...SLATE);
      doc.text(label, x + 10, ly);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(
        ...(tone === "in" ? EMERALD : tone === "out" ? RED : NAVY),
      );
      doc.text(`${document.currency} ${money(value)}`, x + colW - 10, ly, {
        align: "right",
      });
      ly += 16;
    }
    doc.setFillColor(...fill);
    doc.rect(x + 1, startY + blockH - 24, colW - 2, 23, "F");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.setTextColor(...titleColor);
    doc.text("TOTAL", x + 10, startY + blockH - 9);
    doc.text(`${document.currency} ${money(total)}`, x + colW - 10, startY + blockH - 9, {
      align: "right",
    });
  };

  paintBlock(margin, "ADDITIONS", EMERALD, GREEN_FILL, leftLines, additions);
  paintBlock(
    margin + colW + gap,
    "CASHOUTS",
    RED,
    RED_FILL,
    rightLines,
    cashouts,
  );
  return startY + blockH + 16;
}

function baseTableOptions(margin: number, startY: number) {
  return {
    startY,
    margin: { left: margin, right: margin },
    styles: {
      font: "helvetica",
      fontSize: 8,
      textColor: SLATE,
      lineColor: LINE,
      lineWidth: 0.5,
      cellPadding: 4,
      overflow: "linebreak",
    },
    headStyles: {
      fillColor: HEADER_FILL,
      textColor: NAVY,
      fontStyle: "bold",
      fontSize: 7.5,
    },
    footStyles: {
      fillColor: GREEN_FILL,
      textColor: NAVY,
      fontStyle: "bold",
      fontSize: 8,
    },
    alternateRowStyles: { fillColor: [255, 255, 255] },
  };
}

function drawEmpty(
  doc: JsPdfDoc,
  margin: number,
  y: number,
  message: string,
) {
  const pageWidth = doc.internal.pageSize.getWidth();
  const width = pageWidth - margin * 2;
  doc.setDrawColor(...LINE);
  doc.roundedRect(margin, y, width, 28, 4, 4, "S");
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.5);
  doc.setTextColor(...MUTED);
  doc.text(message, margin + width / 2, y + 17, { align: "center" });
  return y + 40;
}

function drawAgentTable(
  doc: JsPdfDoc,
  autoTable: (doc: unknown, opts: unknown) => void,
  document: DailyReportDocumentModel,
  margin: number,
  startY: number,
) {
  if (document.agentReturns.length === 0) {
    return drawEmpty(
      doc,
      margin,
      startY,
      "No field officer float activity for this day.",
    );
  }
  autoTable(doc, {
    ...baseTableOptions(margin, startY),
    head: [
      [
        "Field officer",
        "Float issued",
        "Loans issued",
        "Cash in",
        "Expenses",
        "Returned",
        "Variance",
      ],
    ],
    body: document.agentReturns.map((row) => [
      shortName(row.agentName),
      money(row.amountGiven),
      money(row.amountDisbursed),
      money(row.amountCollected),
      money(row.expensesTotal ?? 0),
      row.amountReturned == null ? "—" : money(row.amountReturned),
      row.variance == null ? "—" : money(row.variance),
    ]),
    foot: [
      [
        "Total",
        money(
          document.agentReturns.reduce((s, r) => s + r.amountGiven, 0),
        ),
        money(
          document.agentReturns.reduce((s, r) => s + r.amountDisbursed, 0),
        ),
        money(
          document.agentReturns.reduce((s, r) => s + r.amountCollected, 0),
        ),
        money(
          document.agentReturns.reduce(
            (s, r) => s + (r.expensesTotal ?? 0),
            0,
          ),
        ),
        money(
          document.agentReturns.reduce(
            (s, r) => s + (r.amountReturned ?? 0),
            0,
          ),
        ),
        money(
          document.agentReturns.reduce((s, r) => s + (r.variance ?? 0), 0),
        ),
      ],
    ],
    columnStyles: {
      1: { halign: "right" },
      2: { halign: "right" },
      3: { halign: "right" },
      4: { halign: "right" },
      5: { halign: "right" },
      6: { halign: "right" },
    },
  });
  return (doc.lastAutoTable?.finalY ?? startY) + 14;
}

function drawLoansTable(
  doc: JsPdfDoc,
  autoTable: (doc: unknown, opts: unknown) => void,
  document: DailyReportDocumentModel,
  margin: number,
  startY: number,
) {
  if (document.loansIssued.length === 0) {
    return drawEmpty(
      doc,
      margin,
      startY,
      "No loans were issued during this business day.",
    );
  }
  autoTable(doc, {
    ...baseTableOptions(margin, startY),
    head: [["Borrower", "Product", "Duration", "Issued by", "Time", "Principal"]],
    body: document.loansIssued.map((row) => [
      row.borrowerName,
      row.product || "—",
      row.durationDays == null ? "—" : `${row.durationDays} days`,
      shortName(row.officerName),
      formatTime(row.issuedAt),
      money(row.principalAmount),
    ]),
    foot: [
      [
        "Total",
        "",
        "",
        "",
        "",
        money(document.loansIssuedPrincipal),
      ],
    ],
    columnStyles: { 5: { halign: "right" } },
  });
  return (doc.lastAutoTable?.finalY ?? startY) + 14;
}

function drawRepaymentsTable(
  doc: JsPdfDoc,
  autoTable: (doc: unknown, opts: unknown) => void,
  document: DailyReportDocumentModel,
  margin: number,
  startY: number,
) {
  if (document.repayments.length === 0) {
    return drawEmpty(
      doc,
      margin,
      startY,
      "No repayments were recorded during this business day.",
    );
  }
  autoTable(doc, {
    ...baseTableOptions(margin, startY),
    head: [["Borrower", "Collected by", "Role", "Time", "Method", "Amount"]],
    body: document.repayments.map((row) => [
      row.borrowerName,
      shortName(row.recordedByName),
      "Field Officer",
      formatTime(row.paidAt),
      methodLabel(row.method),
      money(row.amount),
    ]),
    foot: [["Total", "", "", "", "", money(document.collectionsReceived)]],
    columnStyles: { 5: { halign: "right" } },
  });
  return (doc.lastAutoTable?.finalY ?? startY) + 14;
}

function drawFeesTable(
  doc: JsPdfDoc,
  autoTable: (doc: unknown, opts: unknown) => void,
  document: DailyReportDocumentModel,
  margin: number,
  startY: number,
) {
  if (document.processingFees.length === 0) {
    return drawEmpty(
      doc,
      margin,
      startY,
      "No processing fees were recorded during this business day.",
    );
  }
  autoTable(doc, {
    ...baseTableOptions(margin, startY),
    head: [["Borrower", "Officer", "Time", "Amount"]],
    body: document.processingFees.map((row) => [
      row.borrowerName,
      shortName(row.officerName),
      formatTime(row.receivedAt),
      money(row.amount),
    ]),
    foot: [["Total", "", "", money(document.processingFeesTotal)]],
    columnStyles: { 3: { halign: "right" } },
  });
  return (doc.lastAutoTable?.finalY ?? startY) + 14;
}

function drawExpensesTable(
  doc: JsPdfDoc,
  autoTable: (doc: unknown, opts: unknown) => void,
  document: DailyReportDocumentModel,
  margin: number,
  startY: number,
) {
  if (document.expenses.length === 0) {
    return drawEmpty(
      doc,
      margin,
      startY,
      "No expenses were recorded during this business day.",
    );
  }
  autoTable(doc, {
    ...baseTableOptions(margin, startY),
    head: [["Time", "Type", "Description", "Paid by", "Amount"]],
    body: document.expenses.map((row) => [
      formatTime(row.incurredAt),
      categoryLabel(row.category, row.paidFrom),
      row.description?.trim() || "—",
      shortName(row.agentName || row.recordedByName),
      money(row.amount),
    ]),
    foot: [["Total", "", "", "", money(document.expensesTotal)]],
    columnStyles: { 4: { halign: "right" } },
  });
  return (doc.lastAutoTable?.finalY ?? startY) + 14;
}

function drawVariancesTable(
  doc: JsPdfDoc,
  autoTable: (doc: unknown, opts: unknown) => void,
  document: DailyReportDocumentModel,
  margin: number,
  startY: number,
) {
  autoTable(doc, {
    ...baseTableOptions(margin, startY),
    head: [["Source", "Person", "Status", "Variance"]],
    body: document.variances.map((row) => [
      titleCase(row.source.replaceAll("_", " ")),
      row.personName ? shortName(row.personName) : "—",
      titleCase(row.status.replaceAll("_", " ")),
      money(row.variance),
    ]),
    columnStyles: { 3: { halign: "right" } },
  });
  return (doc.lastAutoTable?.finalY ?? startY) + 14;
}

/** Download a PDF blob as a file. */
export function downloadPdfBlob(blob: Blob, fileName: string) {
  const url = URL.createObjectURL(blob);
  const anchor = window.document.createElement("a");
  anchor.href = url;
  anchor.download = fileName;
  window.document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();
  window.setTimeout(() => URL.revokeObjectURL(url), 1500);
}
