"use client";

import {
  Loader2,
  Maximize2,
  Minimize2,
  Share2,
  ZoomIn,
  ZoomOut,
} from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import {
  dailyReportPdfFileName,
  dailyReportShareMessage,
  downloadPdfBlob,
  REMBEH_BRAND_NAME,
  REMBEH_WEB_URL,
} from "./daily-report-pdf-document";
import { useDailyReportPdf } from "./daily-report-pdf-cache";
import type { DailyReportDocumentModel } from "./daily-reconciliation-report";

const MIN_ZOOM = 0.75;
const MAX_ZOOM = 2.5;
const ZOOM_STEP = 0.15;

export function DailyReportPdfViewer({
  document,
  className = "",
}: {
  document: DailyReportDocumentModel;
  className?: string;
}) {
  const { blob, url, loading, error } = useDailyReportPdf(document);
  const [zoom, setZoom] = useState(1);
  const [sharing, setSharing] = useState(false);
  const [fullscreen, setFullscreen] = useState(false);
  const fileName = useMemo(
    () => dailyReportPdfFileName(document),
    [document],
  );

  useEffect(() => {
    if (!fullscreen) return;
    const onKey = (event: KeyboardEvent) => {
      if (event.key === "Escape") setFullscreen(false);
    };
    window.addEventListener("keydown", onKey);
    const previous = window.document.body.style.overflow;
    window.document.body.style.overflow = "hidden";
    return () => {
      window.removeEventListener("keydown", onKey);
      window.document.body.style.overflow = previous;
    };
  }, [fullscreen]);

  async function sharePdf() {
    if (!blob || sharing) return;
    setSharing(true);
    try {
      const file = new File([blob], fileName, { type: "application/pdf" });
      const message = dailyReportShareMessage(document);
      if (
        typeof navigator !== "undefined" &&
        typeof navigator.share === "function" &&
        (!navigator.canShare || navigator.canShare({ files: [file] }))
      ) {
        await navigator.share({
          title: `Daily Reconciliation Report · ${REMBEH_BRAND_NAME}`,
          text: message,
          files: [file],
        });
        return;
      }
      downloadPdfBlob(blob, fileName);
      try {
        await navigator.clipboard.writeText(message);
      } catch {
        // Clipboard may be blocked; download still succeeded.
      }
    } finally {
      setSharing(false);
    }
  }

  const toolbar = (
    <div className="flex flex-wrap items-center justify-between gap-2 border-b border-[#e6ebf0] bg-[#f8faf9] px-3 py-2.5">
      <div className="min-w-0">
        <p className="truncate text-sm font-bold text-[#0b1220]">PDF report</p>
        <p className="truncate text-[11px] font-medium text-slate-500">
          Generated by {REMBEH_BRAND_NAME} ·{" "}
          {REMBEH_WEB_URL.replace("https://", "")}
        </p>
      </div>
      <div className="flex flex-wrap items-center gap-1.5">
        <button
          type="button"
          disabled={zoom <= MIN_ZOOM}
          onClick={() =>
            setZoom((value) => Math.max(MIN_ZOOM, value - ZOOM_STEP))
          }
          className="inline-flex size-9 items-center justify-center rounded-xl border border-[#e6ebf0] bg-white text-[#0b1220] transition hover:bg-[#f4f7f6] disabled:opacity-40"
          title="Zoom out"
        >
          <ZoomOut className="size-4" />
        </button>
        <button
          type="button"
          onClick={() => setZoom(1)}
          className="inline-flex h-9 min-w-[58px] items-center justify-center rounded-xl border border-[#e6ebf0] bg-white px-2 text-xs font-bold text-[#0b1220] transition hover:bg-[#f4f7f6]"
          title="Reset zoom"
        >
          {Math.round(zoom * 100)}%
        </button>
        <button
          type="button"
          disabled={zoom >= MAX_ZOOM}
          onClick={() =>
            setZoom((value) => Math.min(MAX_ZOOM, value + ZOOM_STEP))
          }
          className="inline-flex size-9 items-center justify-center rounded-xl border border-[#e6ebf0] bg-white text-[#0b1220] transition hover:bg-[#f4f7f6] disabled:opacity-40"
          title="Zoom in"
        >
          <ZoomIn className="size-4" />
        </button>
        <button
          type="button"
          onClick={() => setFullscreen((value) => !value)}
          className="inline-flex size-9 items-center justify-center rounded-xl border border-[#e6ebf0] bg-white text-[#0b1220] transition hover:bg-[#f4f7f6]"
          title={fullscreen ? "Exit full screen" : "Full screen"}
        >
          {fullscreen ? (
            <Minimize2 className="size-4" />
          ) : (
            <Maximize2 className="size-4" />
          )}
        </button>
        <button
          type="button"
          disabled={!blob || sharing}
          onClick={() => void sharePdf()}
          className="inline-flex h-9 items-center gap-1.5 rounded-xl border border-[#e6ebf0] bg-white px-3 text-xs font-bold text-[#0b1220] transition hover:bg-[#f4f7f6] disabled:opacity-40"
          title="Share"
        >
          {sharing ? (
            <Loader2 className="size-3.5 animate-spin" />
          ) : (
            <Share2 className="size-3.5" />
          )}
          Share
        </button>
      </div>
    </div>
  );

  const stage = (
    <div
      className={`relative bg-[#eef2f0] ${fullscreen ? "min-h-0 flex-1" : "min-h-[70vh]"}`}
    >
      {loading ? (
        <div className="absolute inset-0 grid place-items-center">
          <div className="flex flex-col items-center gap-3 text-sm font-semibold text-slate-600">
            <Loader2 className="size-6 animate-spin text-[var(--forest-emerald)]" />
            Preparing report PDF…
          </div>
        </div>
      ) : null}

      {error ? (
        <div className="absolute inset-0 grid place-items-center p-6">
          <p className="max-w-md rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-center text-sm text-red-700">
            {error}
          </p>
        </div>
      ) : null}

      {url && !loading && !error ? (
        <div
          className={`overflow-auto p-3 sm:p-4 ${fullscreen ? "h-full" : "h-[75vh]"}`}
        >
          <div
            className="mx-auto origin-top transition-transform duration-150"
            style={{
              width: `${100 / zoom}%`,
              transform: `scale(${zoom})`,
            }}
          >
            <iframe
              title="Daily reconciliation PDF"
              src={`${url}#toolbar=1&navpanes=0`}
              className={`w-full rounded-lg border border-[#d5ddd8] bg-white shadow-[0_10px_28px_rgba(15,23,42,0.08)] ${
                fullscreen ? "h-[calc(100vh-5.5rem)]" : "h-[72vh]"
              }`}
            />
          </div>
        </div>
      ) : null}
    </div>
  );

  if (fullscreen) {
    return (
      <div className="fixed inset-0 z-[80] flex flex-col bg-white">
        {toolbar}
        {stage}
      </div>
    );
  }

  return (
    <section
      className={`overflow-hidden rounded-[16px] border border-[#e6ebf0] bg-white shadow-[0_12px_28px_rgba(15,23,42,0.05)] ${className}`}
    >
      {toolbar}
      {stage}
    </section>
  );
}
